version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-casa-das-bicicletas
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CASA_DAS_BICICLETAS_PORT=3000
      - CASA_DAS_BICICLETAS_DB_HOST=ep-sweet-silence-a5kcl0mr.us-east-2.aws.neon.tech
      - CASA_DAS_BICICLETAS_DB_PORT=5432
      - CASA_DAS_BICICLETAS_DB_USERNAME=casa-das-bicicletas_owner
      - CASA_DAS_BICICLETAS_DB_PASSWORD=BhIH81JiYOpl
      - CASA_DAS_BICICLETAS_DB_NAME=casa-das-bicicletas
      - CASA_DAS_BICICLETAS_SWAGGER_USERNAME=root
      - CASA_DAS_BICICLETAS_SWAGGER_PASSWORD=root
      - CASA_DAS_BICICLETAS_SWAGGER_TITLE=Casa Das Bicicletas API
      - CASA_DAS_BICICLETAS_SWAGGER_DESCRIPTION=Swagger com endpoints da api
      - CASA_DAS_BICICLETAS_SWAGGER_VERSION=1.0
      - CASA_DAS_BICICLETAS_SALT=12
      - CASA_DAS_BICICLETAS_SECRET_KEY=65bd52691a0f4c3b57819a4b
      - EMAIL_CASA_DAS_BICICLETAS=farciomernandes@gmail.com
      - CASA_DAS_BICICLETAS_AWS_ACCESS_KEY_ID=AKIA4MTWG3OB7OBRQRUG
      - CASA_DAS_BICICLETAS_AWS_SECRET_KEY=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
      - CASA_DAS_BICICLETAS_AWS_REGION=us-east-2
      - CASA_DAS_BICICLETAS_AWS_BUCKET=casa-das-bicicletas
      - CASA_DAS_BICICLETAS_MELHOR_ENVIO_TOKEN_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOWQ2Yzk3NzhiNzRhMWJiMGZkYTkzNTQ5ZTIyNDk5YmVlNWFkODg4MzdjZDZkZWM3ZmQ4M2U1MzFlNzViYmQwOWEwZjI4M2NhNDJjOGM2MzciLCJpYXQiOjE3MTY0MDc0NjkuNDA5ODQ4LCJuYmYiOjE3MTY0MDc0NjkuNDA5ODQ5LCJleHAiOjE3NDc5NDM0NjkuNDAwNjI0LCJzdWIiOiI5YzFiMmEzNi0zOWQ0LTQzYzgtYjhkMy01NzY0OTkxNmYyNDIiLCJzY29wZXMiOlsic2hpcHBpbmctY2FsY3VsYXRlIl19.r0H7hUTaKcTsQvbyDrdthpX9qlc8IrXEbbAinyNuxFFG0GnouLocWQLnesulSIBRZJtrMMB3VPJr-sjM1zI8j1_X92ofKLpYVST88pK6V9wnymVCVi0EHxT9J28Lj9wKV8KsWUpwfOaIsOwv87tRG_ieDk3dgTz8tZNU6b1KKILdejY_g3s1g2zECwI4uI06IdjZ16PPFZ5UchpeU9X8uFHjh-12RTVQ4O8QCrglZ9v2MlTSdY-8tDxmzqVa9r4gkY26BT2RjDbZrPp8m8944Wqzpe-pIiRYVSsZ13OQbgUSr9RJ8FEvO1cPq6jx-reXjM1-kwMrorykU8NR0Gf961JqncpIa8-efvkuqCc4O0Fhcyvk7wr-yvquUZrw3Jo3EZINugakLupku0Z0FikqoFjh9mGPadZeHb_JK6m6YewJtJaOdFUFv0r_gC8n-mLY6rc3TCsRvOfhiJ0f1SId0I096nBqUIIYTBY_9N5GsatWs-U4ggyp-gKL-e_ZT-juKAty1RjXol7NPccTiJiSmVab-gEBdPm0oorSz4XCozkInLwmE2Nl94S3lH5_eoLmlLxKZZugFsewKQWC4OzZRq6DnNsXm_84hbqO8pB8SFqlSpy3-YWG7rkqA3PBkdhyGLBRA7obMUf2UoYVaFXSFDr8g8q7RFRud0Ajqqr-uYU
      - CASA_DAS_BICICLETAS_MELHOR_ENVIO_URL=https://www.melhorenvio.com.br/api/v2
      - CASA_DAS_BICICLETAS_ASAAS_API_URL=https://sandbox.asaas.com/api/v3
      - CASA_DAS_BICICLETAS_ASAAS_API_ACCESS_TOKEN="\$aact_YTU5YTE0M2M2N2I4MTliNzk0YTI5N2U5MzdjNWZmNDQ6OjAwMDAwMDAwMDAwMDAwNzkyNDM6OiRhYWNoXzQxYTg2ODJlLTRhNjEtNDYzOS05MzFlLWZhMzE3MDljYmI2NQ=="
      - MERCADO_PAGO_ACCESS_TOKEN=TEST-8244721430585076-042514-8a9fefba501c83e21511ceb31a751e4a-579386007
      - MERCADO_PAG0_URL=https://api.mercadopago.com/v1
    networks:
      - appworks

networks:
  appworks:
    driver: bridge
