version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: pg-casa-das-bicicletas
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=casa-das-bicicletas
    networks:
      - appworks
  
networks:
  appworks:
    driver: bridge