version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-casa-das-bicicletas
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - appworks

networks:
  appworks:
    driver: bridge